---
- name: Format drive.
  community.general.filesystem: 
    dev: "{{ item.key }}"
    fstype: ext4
  with_dict: "{{ drives }}"

- name: Create path if doesn't exist.
  file:
    path: "{{ item.value }}"
    state: directory
  with_dict: "{{ drives }}"

- name: Mount drive.
  ansible.posix.mount:
    src: "{{ item.key }}"
    path: "{{ item.value }}"
    fstype: ext4
    state: present
  with_dict: "{{ drives }}"

- name: Download the MinIO binary.
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: '0750'

- name: Set permissions on MinIO binary.
  file:
    path: /usr/local/bin/minio
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_user }}"

- name: Template ENV file.
  template:
    src: minio.env.j2
    dest: /etc/default/minio.env
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_user }}"
    mode: "0600"

- name: Template service file.
  template:
    src: minio.service.j2
    dest: /lib/systemd/system/minio.service
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_user }}"
    mode: "0600"

- name: Start MinIO.
  systemd:
    name: minio
    daemon_reload: yes
    state: started
    enabled: yes